// <auto-generated />
namespace Experion.Marina.Data.Services.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class answertableadded1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(answertableadded1));
        
        string IMigrationMetadata.Id
        {
            get { return "201702220955372_answertableadded1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
